<?php

namespace TravelBundle\Repository;
use TravelBundle\Entity\Search;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBy(Search $search){
        return $this->createQueryBuilder('place')
            ->where('place.country = :country')
            ->andWhere('place.city = :city')
            ->andWhere('place.capacity >= :capacity')
            ->innerJoin('place.reservations', 'reservations')
            ->andWhere('(reservations.startDate >= :endDate AND reservations.startDate >= :startDate)
            OR (reservations.startDate <= :endDate AND reservations.startDate <= :startDate)')
            ->setParameters([
                ':country' => $search->getCountry(),
                ':city' => $search->getCity(),
                ':capacity' => $search->getCapacity(),
                ':endDate' => $search->getEndDate(),
                ':startDate' => $search->getStartDate()])
            ->getQuery()
            ->getResult();
    }
}
