<?php

namespace TravelBundle\Repository;
use Doctrine\ORM\Query\Expr\Join;
use TravelBundle\Entity\Search;

/**
 * PlaceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlaceRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllBy(Search $search){
        return $this->createQueryBuilder('place')
            ->innerJoin('place.address', 'address')
            ->where('address.country = :country')
            ->andWhere('address.city = :city')
            ->andWhere('place.capacity >= :capacity')
            ->leftJoin('place.reservations', 'reservations')
            ->andWhere('reservations IS NULL OR ((reservations.startDate >= :endDate AND reservations.startDate >= :startDate) OR
                        (reservations.startDate <= :endDate AND reservations.startDate <= :startDate))')
            ->andWhere('place.owner != :user')
            ->setParameters([
                ':country' => $search->getCountry(),
                ':city' => $search->getCity(),
                ':capacity' => $search->getCapacity(),
                ':endDate' => $search->getEndDate(),
                ':startDate' => $search->getStartDate(),
                ':user' => $search->getUser()
            ])
            ->getQuery()
            ->getResult();
    }
}
